name: Metrics Blusutils
on:
  #push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Blusutils
          base: header
          plugin_traffic: yes
          plugin_introduction: yes
          commits_authoring: firstname lastname, username
          filename: github-metrics-blusutils.svg
          token: ${{ secrets.ACC_SECRET }}
