name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3,15,21 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_MSG: "Updated the Wakatime section in Readme" 
